title: Blood on the Clocktower Online
theme: minima
url: https://release.botc.app

plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  # - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

header_pages:
  - index.md
  - resources/index.md

readme_index:
  with_frontmatter: true
