name: App Feature Suggestion
description: Suggest a new feature for the app.
title: "[FEATURE]: "
labels: ["feature", "triage"]
projects: ["ThePandemoniumInstitute/botc-release"]
body:
  - type: markdown
    attributes:
      value: You may suggest a new app feature here. Please try to be as detailed as possible with your description, as this will make it easier for us to understand your suggestion.
  - type: textarea
    attributes:
      label: What problem are you trying to solve?
      description: Is your feature request related to a problem?
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: How does your idea improve or change the app?
      placeholder: A clear and concise description of what you want to happen. Ex. I'd like to create a [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives you have considered
      description: What alternatives to the feature have been considered?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Comments
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: After submitting the suggestion, feel free to attach any images or concept sketches to the created ticket that might help with implementing the feature! Thank you.
